"""Adapter for optional fitburst-backed scattering model fits.

This module keeps the optional :mod:`fitburst` dependency behind a small FLITS
interface. The session layer passes in an already cropped/reduced dynamic
spectrum for the selected frequency band; this adapter normalizes each channel
against off-pulse bins, fits only the selected event window, and returns
model-based intrinsic width and scattering-time diagnostics.

If fitburst is not installed or a fit cannot be constrained, callers receive a
structured :class:`FitburstScatteringResult` failure instead of an import-time
exception.
"""

from __future__ import annotations

import io
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from flits.models import ScatteringFitDiagnostics

try:
    from fitburst.analysis.fitter import LSFitter
    from fitburst.analysis.model import SpectrumModeler
except Exception:  # pragma: no cover - optional runtime dependency
    LSFitter = None
    SpectrumModeler = None


MIN_FIT_CHANNELS = 4
MIN_FIT_TIME_BINS = 16
MIN_WEIGHT_BINS = 8
FIT_PARAMETERS = ("amplitude", "arrival_time", "burst_width", "scattering_timescale")
FIXED_PARAMETERS = ("dm", "dm_index", "scattering_index", "spectral_index", "spectral_running")


@dataclass(frozen=True)
class FitburstRequestConfig:
    """Configuration for a fitburst scattering-fit request.

    Parameters
    ----------
    num_components
        Number of burst components to pass to fitburst.
    fixed_parameters
        Fitburst parameter names that should be held fixed during the
        optimizer run. By default the adapter varies amplitude, arrival time,
        intrinsic width, and scattering timescale while fixing DM, scattering
        index, and spectral-shape terms.
    initial_parameters
        Optional fitburst parameter overrides. Values should use fitburst's
        native units, including seconds for time-like parameters and MHz for
        ``ref_freq``. Keys not generated by the adapter are ignored.
    bounds
        Optional serialized bounds payload. This field is preserved in request
        dictionaries for API compatibility, but the current adapter does not
        apply it to ``LSFitter``.

    Notes
    -----
    The dataclass is intentionally JSON-like so web requests can round-trip
    through :meth:`to_dict` and :meth:`from_dict`.
    """

    num_components: int = 1
    fixed_parameters: list[str] = field(default_factory=lambda: ["dm", "dm_index", "scattering_index", "spectral_index", "spectral_running"])
    initial_parameters: dict[str, list[float]] | None = None
    bounds: dict[str, list[tuple[float, float]]] | None = None

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-compatible request payload."""
        return {
            "num_components": int(self.num_components),
            "fixed_parameters": list(self.fixed_parameters),
            "initial_parameters": self.initial_parameters,
            "bounds": self.bounds,
        }

    @classmethod
    def from_dict(cls, payload: dict[str, Any] | None) -> "FitburstRequestConfig":
        """Build a request config from a web/API payload."""
        if payload is None:
            return cls()
        try:
            num_components = int(payload.get("num_components", 1))
        except (TypeError, ValueError):
            num_components = 1
        return cls(
            num_components=max(1, num_components),
            fixed_parameters=[str(flag) for flag in payload.get("fixed_parameters", ["dm", "dm_index", "scattering_index", "spectral_index", "spectral_running"])],
            initial_parameters=payload.get("initial_parameters"),
            bounds=payload.get("bounds"),
        )


@dataclass(frozen=True)
class FitburstScatteringResult:
    """Result returned by the fitburst adapter.

    Parameters
    ----------
    status
        Machine-readable fit status. ``"ok"`` indicates a converged fit; other
        values describe structured failure modes.
    message
        Human-readable fitburst or adapter message, when available.
    width_ms_model
        Fitted intrinsic burst width for the first component, in milliseconds.
        Full component arrays are stored in ``diagnostics.bestfit_parameters``.
    width_uncertainty_ms
        Fitburst uncertainty for ``width_ms_model``, in milliseconds.
    tau_sc_ms
        Fitted scattering timescale for the first component, in milliseconds.
    tau_uncertainty_ms
        Fitburst uncertainty for ``tau_sc_ms``, in milliseconds.
    diagnostics
        Full diagnostic payload, including parameter dictionaries, fit
        statistics, model/data dynamic spectra, and residual profiles.
    """

    status: str
    message: str | None
    width_ms_model: float | None
    width_uncertainty_ms: float | None
    tau_sc_ms: float | None
    tau_uncertainty_ms: float | None
    diagnostics: ScatteringFitDiagnostics


def fit_scattering_selected_band(
    *,
    selected_band: np.ndarray,
    freqs_mhz: np.ndarray,
    time_axis_ms: np.ndarray,
    event_rel_start: int,
    event_rel_end: int,
    offpulse_bins: np.ndarray,
    tsamp_ms: float,
    peak_rel_bin: int | None,
    width_guess_ms: float | None,
    config: "FitburstRequestConfig" | None = None,
) -> FitburstScatteringResult:
    """Fit intrinsic width and scattering time for a selected dynamic spectrum.

    Parameters
    ----------
    selected_band
        Dynamic spectrum with shape ``(n_channels, n_time)``. Rows correspond
        to the selected frequency channels and columns to the current
        crop/reduced time grid. Non-finite samples are replaced by each
        channel's baseline during normalization.
    freqs_mhz
        Frequency axis in MHz with length ``n_channels``. The order should
        match ``selected_band`` rows.
    time_axis_ms
        Time axis in milliseconds with length ``n_time``. The adapter converts
        the fitted event window to seconds before constructing the fitburst
        model.
    event_rel_start, event_rel_end
        Half-open event window, in selected-band time-bin coordinates. Only
        this interval is passed to ``LSFitter``.
    offpulse_bins
        Time-bin indices used as the per-channel reference for baseline and
        noise estimation. If empty, the full channel is used as the reference.
    tsamp_ms
        Effective time resolution of the selected/reduced grid, in
        milliseconds.
    peak_rel_bin
        Optional peak bin in selected-band coordinates. If omitted, the peak is
        estimated from the mean normalized event profile.
    width_guess_ms
        Optional initial intrinsic-width guess in milliseconds. If omitted or
        non-finite, the adapter seeds the width from the event duration and
        time resolution.
    config
        Optional fitburst request configuration. Defaults to
        :class:`FitburstRequestConfig`.

    Returns
    -------
    FitburstScatteringResult
        Structured fit result. Possible ``status`` values are ``"ok"``,
        ``"fitburst_unavailable"``, ``"insufficient_data"``,
        ``"insufficient_time_bins"``, ``"insufficient_channels"``,
        ``"insufficient_signal"``, and ``"fit_failed"``.

    Notes
    -----
    The scalar width and scattering-time fields report the first component.
    For multi-component fits, inspect ``diagnostics.bestfit_parameters`` for
    the full fitburst parameter arrays.
    """
    if SpectrumModeler is None or LSFitter is None:
        return _failed_result(
            status="fitburst_unavailable",
            message="fitburst is not available in the active Python environment.",
        )

    data = np.asarray(selected_band, dtype=float)
    freqs = np.asarray(freqs_mhz, dtype=float)
    time_axis_ms = np.asarray(time_axis_ms, dtype=float)
    offpulse_bins = np.asarray(offpulse_bins, dtype=int)

    if data.ndim != 2 or data.shape[0] == 0 or data.shape[1] == 0:
        return _failed_result(status="insufficient_data", message="No selected-band data are available for fitting.")
    if data.shape[1] < MIN_FIT_TIME_BINS:
        return _failed_result(
            status="insufficient_time_bins",
            message=f"At least {MIN_FIT_TIME_BINS} time bins are required for scattering fits.",
        )

    normalized_data, good_freq = _normalize_dynamic_spectrum(data, offpulse_bins)
    good_channel_count = int(np.count_nonzero(good_freq))
    if good_channel_count < MIN_FIT_CHANNELS:
        return _failed_result(
            status="insufficient_channels",
            message=f"At least {MIN_FIT_CHANNELS} unmasked channels are required for scattering fits.",
        )


    event_slice = np.asarray(
        np.nanmean(normalized_data[good_freq, event_rel_start:event_rel_end], axis=0),
        dtype=float,
    )
    if event_slice.size == 0 or not np.isfinite(event_slice).any():
        return _failed_result(
            status="insufficient_signal",
            message="The selected event window does not contain a stable signal for fitting.",
        )

    if peak_rel_bin is None:
        peak_rel_bin = int(event_rel_start + np.nanargmax(event_slice))
    peak_rel_bin = max(0, min(int(peak_rel_bin), data.shape[1] - 1))

    if config is None:
        config = FitburstRequestConfig()

    initial_parameters = _initial_parameters(
        normalized_data=normalized_data,
        freqs_mhz=freqs,
        time_axis_ms=time_axis_ms,
        tsamp_ms=float(tsamp_ms),
        peak_rel_bin=peak_rel_bin,
        event_rel_start=int(event_rel_start),
        event_rel_end=int(event_rel_end),
        width_guess_ms=width_guess_ms,
        num_components=config.num_components,
    )
    
    if config.initial_parameters:
        initial_parameters = _apply_initial_parameter_overrides(
            defaults=initial_parameters,
            overrides=config.initial_parameters,
            num_components=config.num_components,
        )

    fit_data = normalized_data[:, event_rel_start:event_rel_end]
    fit_time_axis_ms = time_axis_ms[event_rel_start:event_rel_end]
    times_sec = (fit_time_axis_ms - float(time_axis_ms[0])) / 1e3
    
    model = SpectrumModeler(
        freqs,
        times_sec,
        dm_incoherent=0.0,
        num_components=config.num_components,
        is_dedispersed=True,
    )
    model.update_parameters(initial_parameters)
    fitter = LSFitter(
        fit_data,
        model,
        good_freq=good_freq,
        weighted_fit=False,
    )
    with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
        fitter.fix_parameter(config.fixed_parameters)
        fitter.fit()

    results = getattr(fitter, "results", None)
    if results is None or not getattr(results, "success", False):
        message = None
        if results is not None:
            message = str(getattr(results, "message", "") or "").strip() or None
        return _failed_result(
            status="fit_failed",
            message=message or "fitburst could not converge for the current selection.",
            initial_parameters=initial_parameters,
            fit_statistics=getattr(fitter, "fit_statistics", {}),
        )

    fit_statistics = dict(getattr(fitter, "fit_statistics", {}))
    bestfit_parameters = dict(fit_statistics.get("bestfit_parameters") or {})
    bestfit_uncertainties = dict(fit_statistics.get("bestfit_uncertainties") or {})
    fit_parameters = list(getattr(fitter, "fit_parameters", []))
    full_best_parameters = dict(initial_parameters)
    full_best_parameters.update(bestfit_parameters)
    
    model.update_parameters(full_best_parameters)
    model_dynamic_spectrum = np.asarray(model.compute_model(data=fit_data), dtype=float)

    data_profile = np.nanmean(fit_data[good_freq, :], axis=0)
    model_profile = np.mean(model_dynamic_spectrum[good_freq, :], axis=0)
    residual_profile = data_profile - model_profile
    
    data_freq_profile = np.nanmean(fit_data, axis=1)
    model_freq_profile = np.mean(model_dynamic_spectrum, axis=1)
    residual_freq_profile = data_freq_profile - model_freq_profile

    bad_freq = ~good_freq
    fit_data[bad_freq, :] = np.nan
    model_dynamic_spectrum[bad_freq, :] = np.nan
    data_freq_profile[bad_freq] = np.nan
    model_freq_profile[bad_freq] = np.nan
    residual_freq_profile[bad_freq] = np.nan

    width_sec = _parameter_value(full_best_parameters, "burst_width")
    tau_sec = _parameter_value(full_best_parameters, "scattering_timescale")
    width_uncertainty_sec = _parameter_value(bestfit_uncertainties, "burst_width")
    tau_uncertainty_sec = _parameter_value(bestfit_uncertainties, "scattering_timescale")

    diagnostics = ScatteringFitDiagnostics(
        status="ok",
        message=str(getattr(results, "message", "") or "").strip() or None,
        fitter="fitburst",
        component_count=config.num_components,
        fit_parameters=fit_parameters,
        fixed_parameters=config.fixed_parameters,
        initial_parameters=initial_parameters,
        bestfit_parameters=full_best_parameters,
        bestfit_uncertainties=bestfit_uncertainties,
        fit_statistics=_sanitize_fit_statistics(fit_statistics),
        freq_axis_mhz=np.asarray(freqs, dtype=float),
        time_axis_ms=np.asarray(fit_time_axis_ms, dtype=float),
        data_dynamic_spectrum_sn=np.asarray(fit_data, dtype=float),
        model_dynamic_spectrum_sn=np.asarray(model_dynamic_spectrum, dtype=float),
        residual_dynamic_spectrum_sn=np.asarray(fit_data - model_dynamic_spectrum, dtype=float),
        data_profile_sn=np.asarray(data_profile, dtype=float),
        model_profile_sn=np.asarray(model_profile, dtype=float),
        residual_profile_sn=np.asarray(residual_profile, dtype=float),
        data_freq_profile_sn=np.asarray(data_freq_profile, dtype=float),
        model_freq_profile_sn=np.asarray(model_freq_profile, dtype=float),
        residual_freq_profile_sn=np.asarray(residual_freq_profile, dtype=float),
    )
    return FitburstScatteringResult(
        status="ok",
        message=diagnostics.message,
        width_ms_model=None if width_sec is None else float(width_sec * 1e3),
        width_uncertainty_ms=None if width_uncertainty_sec is None else float(width_uncertainty_sec * 1e3),
        tau_sc_ms=None if tau_sec is None else float(tau_sec * 1e3),
        tau_uncertainty_ms=None if tau_uncertainty_sec is None else float(tau_uncertainty_sec * 1e3),
        diagnostics=diagnostics,
    )


def _normalize_dynamic_spectrum(
    data: np.ndarray,
    offpulse_bins: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Normalize each frequency channel to off-pulse signal-to-noise units.

    Parameters
    ----------
    data
        Dynamic spectrum with shape ``(n_channels, n_time)``.
    offpulse_bins
        Reference time bins used to estimate each channel's baseline and noise.

    Returns
    -------
    normalized, good_freq
        ``normalized`` has the same shape as ``data``. ``good_freq`` marks
        channels with finite samples and positive finite noise estimates; other
        rows remain zero-filled and are excluded from the fit.
    """
    normalized = np.zeros_like(data, dtype=float)
    good_freq = np.zeros(data.shape[0], dtype=bool)
    for index in range(data.shape[0]):
        row = np.asarray(data[index], dtype=float)
        finite_row = row[np.isfinite(row)]
        if finite_row.size == 0:
            continue
        reference = row[offpulse_bins] if offpulse_bins.size else row
        finite_reference = reference[np.isfinite(reference)]
        if finite_reference.size == 0:
            finite_reference = finite_row
        baseline = float(np.nanmean(finite_reference))
        sigma = float(np.nanstd(finite_reference))
        if not np.isfinite(sigma) or sigma <= 0:
            continue
        filled = np.where(np.isfinite(row), row, baseline)
        normalized[index, :] = (filled - baseline) / sigma
        good_freq[index] = True
    return normalized, good_freq


def _contiguous_weight_range(
    *,
    num_time: int,
    event_rel_start: int,
    event_rel_end: int,
) -> list[int] | None:
    candidates = [
        [0, max(0, int(event_rel_start))],
        [min(num_time, int(event_rel_end)), int(num_time)],
    ]
    candidates = [item for item in candidates if item[1] - item[0] >= MIN_WEIGHT_BINS]
    if not candidates:
        return None
    return max(candidates, key=lambda item: item[1] - item[0])


def _initial_parameters(
    *,
    normalized_data: np.ndarray,
    freqs_mhz: np.ndarray,
    time_axis_ms: np.ndarray,
    tsamp_ms: float,
    peak_rel_bin: int,
    event_rel_start: int,
    event_rel_end: int,
    width_guess_ms: float | None,
    num_components: int = 1,
) -> dict[str, list[float]]:
    """Seed the fitburst parameter dictionary from the selected event.

    The adapter estimates the log-amplitude from the normalized event peak,
    places the initial arrival time at the selected peak bin, converts width
    and scattering guesses from milliseconds to fitburst's seconds convention,
    uses the minimum selected frequency as ``ref_freq``, and seeds fixed DM and
    spectral terms with neutral/default values.
    """
    event_window = normalized_data[:, event_rel_start:event_rel_end]
    peak_value = float(np.nanmax(event_window)) if event_window.size and np.isfinite(event_window).any() else 1.0
    amplitude_guess = float(np.log10(max(peak_value, 1e-2)))
    arrival_time_sec = float((time_axis_ms[peak_rel_bin] - float(time_axis_ms[0])) / 1e3)
    width_ms = float(width_guess_ms) if width_guess_ms is not None and np.isfinite(width_guess_ms) else max(tsamp_ms * 2.0, (event_rel_end - event_rel_start) * tsamp_ms / 6.0)
    width_ms = max(width_ms, tsamp_ms)
    tau_ms = max(tsamp_ms, width_ms / 4.0)
    ref_freq = float(np.min(freqs_mhz))
    return {
        "amplitude": [amplitude_guess] * num_components,
        "arrival_time": [arrival_time_sec] * num_components,
        "burst_width": [float(width_ms / 1e3)] * num_components,
        "dm": [0.0] * num_components,
        "dm_index": [-2.0] * num_components,
        "ref_freq": [ref_freq] * num_components,
        "scattering_timescale": [float(tau_ms / 1e3)] * num_components,
        "scattering_index": [-4.0] * num_components,
        "spectral_index": [0.0] * num_components,
        "spectral_running": [0.0] * num_components,
    }


def _apply_initial_parameter_overrides(
    *,
    defaults: dict[str, list[float]],
    overrides: dict[str, Any],
    num_components: int,
) -> dict[str, list[float]]:
    """Return fitburst initial parameters with JSON/API overrides sanitized.

    The web UI submits per-component guesses as plain JSON numbers. This helper
    keeps the adapter tolerant of scalar values, short arrays, long arrays, and
    non-finite entries while ensuring fitburst receives exactly one numeric
    value per component for every known parameter.
    """
    coerced = {key: _coerce_parameter_values(values, values, num_components) for key, values in defaults.items()}
    for key, values in overrides.items():
        if key not in defaults:
            continue
        coerced[key] = _coerce_parameter_values(values, defaults[key], num_components)
    return coerced


def _coerce_parameter_values(
    values: Any,
    defaults: list[float],
    num_components: int,
) -> list[float]:
    component_count = max(1, int(num_components))
    default_array = np.asarray(defaults, dtype=float).ravel()
    if default_array.size == 0:
        default_array = np.zeros(component_count, dtype=float)
    if default_array.size < component_count:
        default_array = np.pad(default_array, (0, component_count - default_array.size), mode="edge")
    default_array = default_array[:component_count]

    try:
        value_array = np.asarray(values, dtype=float).ravel()
    except (TypeError, ValueError):
        return [float(value) for value in default_array]

    if value_array.size == 0:
        return [float(value) for value in default_array]
    if value_array.size == 1:
        value_array = np.repeat(value_array[0], component_count)
    elif value_array.size < component_count:
        value_array = np.concatenate([value_array, default_array[value_array.size : component_count]])
    elif value_array.size > component_count:
        value_array = value_array[:component_count]

    value_array = np.where(np.isfinite(value_array), value_array, default_array)
    return [float(value) for value in value_array]


def _parameter_value(parameters: dict[str, list[float] | None], key: str) -> float | None:
    values = parameters.get(key)
    if not values:
        return None
    value = values[0]
    if value is None or not np.isfinite(value):
        return None
    return float(value)


def _sanitize_fit_statistics(
    fit_statistics: dict[str, object],
) -> dict[str, float | int | None]:
    """Keep only scalar, JSON-safe fit statistics for diagnostics exports."""
    payload: dict[str, float | int | None] = {}
    for key in (
        "chisq_initial",
        "chisq_final",
        "chisq_final_reduced",
        "snr",
        "num_freq",
        "num_freq_good",
        "num_fit_parameters",
        "num_observations",
        "num_time",
    ):
        value = fit_statistics.get(key)
        if value is None:
            payload[key] = None
        elif isinstance(value, (np.integer, int)):
            payload[key] = int(value)
        elif isinstance(value, (np.floating, float)):
            payload[key] = None if not np.isfinite(value) else float(value)
    return payload


def _failed_result(
    *,
    status: str,
    message: str | None,
    initial_parameters: dict[str, list[float]] | None = None,
    fit_statistics: dict[str, object] | None = None,
) -> FitburstScatteringResult:
    """Return a structured failure result with empty diagnostic arrays."""
    diagnostics = ScatteringFitDiagnostics(
        status=status,
        message=message,
        fitter="fitburst" if SpectrumModeler is not None and LSFitter is not None else None,
        component_count=1,
        fit_parameters=list(FIT_PARAMETERS),
        fixed_parameters=list(FIXED_PARAMETERS),
        initial_parameters=initial_parameters or {},
        bestfit_parameters={},
        bestfit_uncertainties={},
        fit_statistics=_sanitize_fit_statistics(fit_statistics or {}),
        freq_axis_mhz=np.array([], dtype=float),
        time_axis_ms=np.array([], dtype=float),
        data_dynamic_spectrum_sn=np.empty((0, 0), dtype=float),
        model_dynamic_spectrum_sn=np.empty((0, 0), dtype=float),
        residual_dynamic_spectrum_sn=np.empty((0, 0), dtype=float),
        data_profile_sn=np.array([], dtype=float),
        model_profile_sn=np.array([], dtype=float),
        residual_profile_sn=np.array([], dtype=float),
    )
    return FitburstScatteringResult(
        status=status,
        message=message,
        width_ms_model=None,
        width_uncertainty_ms=None,
        tau_sc_ms=None,
        tau_uncertainty_ms=None,
        diagnostics=diagnostics,
    )
